[package]
name = "vaporetto-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
vaporetto = "=0.6.5"

[build-dependencies]
vaporetto = { version = "=0.6.5", features = ["kytea"] }

[profile.release.build-override]
opt-level = 3
